CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE noms_restaurants 
    ADD COLUMN 
        nominated_by_user INTEGER REFERENCES users(id)
        ON DELETE SET NULL;